//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_escritorio_Chrysallis2
{
    using System;
    using System.Collections.Generic;
    
    public partial class assistir
    {
        public int id_soci { get; set; }
        public int id_esdeveniment { get; set; }
        public Nullable<int> num_familiars { get; set; }
        public Nullable<int> valoració { get; set; }
        public string comentari { get; set; }
    
        public virtual Soci Soci { get; set; }
        public virtual esdeveniments esdeveniments { get; set; }
    }
}
