//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_escritorio_Chrysallis2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChrysallisEntities : DbContext
    {
        public ChrysallisEntities()
            : base("name=ChrysallisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assistir> assistir { get; set; }
        public virtual DbSet<comunitats> comunitats { get; set; }
        public virtual DbSet<documents> documents { get; set; }
        public virtual DbSet<esdeveniments> esdeveniments { get; set; }
        public virtual DbSet<notificacions> notificacions { get; set; }
        public virtual DbSet<Soci> Soci { get; set; }
    }
}
